#!/bin/sh

[ ! -x "$(command -v afplay)" ] && exit 1
[ ! -f "$EMPTY_FILE_PATH" ] && exit 1

[ -z "$EMPTY_FILE_PATH" ] && EMPTY_FILE_PATH="$(cd "$(dirname "$0")" && pwd)/../Resources/empty.wav"
[ -z "$DELAY"] && DELAY=5

main() {
	while true; do 
		afplay "$EMPTY_FILE_PATH" 2>/dev/null
		sleep $DELAY
	done

	exit 0
}

main &
